import json
import asyncio
from playwright.async_api import async_playwright
from backend.config.config_manager import config_manager

RECORD_SCRIPT_JS = """
(function() {
    if (window.is_recording_initialized) return;
    window.is_recording_initialized = true;
    console.log('AI Automation Recorder: Initializing...');

    const isSensitive = (el) => {
        if (el.type === 'password') return true;
        const sensitiveKeywords = ['password', 'passwd', 'pwd', 'secret', 'token', 'creditcard', 'cvv'];
        const attrs = ['name', 'id', 'placeholder', 'aria-label'];
        for (const attr of attrs) {
            const val = el.getAttribute(attr)?.toLowerCase() || '';
            if (sensitiveKeywords.some(k => val.includes(k))) return true;
        }
        if (el.id) {
            const label = document.querySelector(`label[for="${el.id}"]`);
            if (label) {
                const labelText = label.innerText.toLowerCase();
                if (sensitiveKeywords.some(k => labelText.includes(k))) return true;
            }
        }
        return false;
    };

    const getSelector = (el) => {
        if (!el || el.tagName === 'HTML') return '';
        if (el.tagName === 'BODY') return 'body';

        // 1. Data Attributes (Strongest)
        const testIdAttrs = ['data-testid', 'data-test', 'data-qa', 'data-cy', 'data-automation-id'];
        for (const attr of testIdAttrs) {
            const val = el.getAttribute(attr);
            if (val) return `[${attr}='${val}']`;
        }
        
        // 2. ID (if stable - not auto-generated by frameworks)
        if (el.id && !el.id.match(/[0-9]{5,}/) && !/^(ember|react|vue|__)/i.test(el.id)) {
            return `#${el.id}`;
        }
        
        // 3. Input-specific attributes
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.tagName === 'SELECT') {
            if (el.name) return `${el.tagName.toLowerCase()}[name='${el.name}']`;
            if (el.placeholder) return `${el.tagName.toLowerCase()}[placeholder='${el.placeholder}']`;
        }

        // 4. ARIA Label
        const ariaLabel = el.getAttribute('aria-label');
        if (ariaLabel) return `${el.tagName.toLowerCase()}[aria-label='${ariaLabel}']`;

        // 5. Role + Text (Semantic)
        const role = el.getAttribute('role');
        const text = el.innerText?.trim();
        if (text && text.length > 0 && text.length < 60) {
             const safeText = text.replace(/'/g, "\\'").replace(/\n/g, ' ').substring(0, 40);
             if (['BUTTON', 'A', 'LABEL', 'H1', 'H2', 'H3', 'SPAN'].includes(el.tagName)) {
                 return `//${el.tagName.toLowerCase()}[contains(normalize-space(.), '${safeText}')]`;
             }
             if (role) {
                 return `//*[@role='${role}' and contains(normalize-space(.), '${safeText}')]`;
             }
        }

        // 6. Descriptive Path fallback (CSS)
        let path = el.tagName.toLowerCase();
        if (el.className && typeof el.className === 'string') {
            const classes = el.className.split(/[ ]+/).filter(c => c && !/^(v-|active|hover|focus|selected)/i.test(c)).slice(0, 2);
            if (classes.length > 0) path += '.' + classes.join('.');
        }

        if (el.parentNode && el.parentNode.tagName !== 'HTML' && el.parentNode.tagName !== 'BODY') {
            const siblings = Array.from(el.parentNode.children).filter(s => s.tagName === el.tagName);
            if (siblings.length > 1) {
                const index = siblings.indexOf(el) + 1;
                path += `:nth-of-type(${index})`;
            }
            const parentSelector = getSelector(el.parentNode);
            if (parentSelector && !parentSelector.startsWith('/') && !parentSelector.startsWith('(')) {
                return parentSelector + ' > ' + path;
            }
        }

        // 7. Last resort: Full XPath (Iterative to avoid recursion issues)
        const getXPath = (node) => {
            const parts = [];
            while (node && node.nodeType === Node.ELEMENT_NODE) {
                if (node.id && !node.id.match(/[0-9]{5,}/)) {
                    parts.unshift(`//*[@id='${node.id}']`);
                    return parts.join('');
                }
                let index = 0;
                let sibling = node.previousSibling;
                while (sibling) {
                    if (sibling.nodeType === Node.ELEMENT_NODE && sibling.tagName === node.tagName) {
                        index++;
                    }
                    sibling = sibling.previousSibling;
                }
                const tagName = node.tagName.toLowerCase();
                const pathPart = index > 0 ? `${tagName}[${index + 1}]` : tagName;
                parts.unshift(pathPart);
                node = node.parentNode;
            }
            return '/' + parts.join('/');
        };
        return getXPath(el);
    };

    let lastAction = null;
    const logAction = async (data) => {
        // Prevent duplicate consecutive actions with same data (ignore timestamp for comparison)
        const currentAction = JSON.stringify({ ...data, url: window.location.href });
        if (lastAction === currentAction) return;
        
        // For TYPE actions, only store the last state for a particular selector to avoid keypress flood
        if (data.action === 'TYPE' && lastAction) {
            const last = JSON.parse(lastAction);
            if (last.action === 'TYPE' && last.selector === data.selector) {
                // Skip if it's the same field, but don't set lastAction yet so we capture the final value on blur/change
            }
        }

        lastAction = currentAction;

        if (window.emitRecorderAction) {
            try {
                await window.emitRecorderAction({
                    ...data,
                    timestamp: Date.now(),
                    url: window.location.href
                });
            } catch (e) {
                console.error('AI Automation Recorder: Failed to emit action', e);
            }
        }
    };

    document.addEventListener('click', (e) => {
        if (['INPUT', 'SELECT', 'TEXTAREA'].includes(e.target.tagName)) return;
        const selector = getSelector(e.target);
        logAction({ action: 'CLICK', selector, text: e.target.innerText?.trim().substring(0, 50) });
    }, true);

    let typeTimeout = null;
    const handleInputChange = (e) => {
        if (['INPUT', 'SELECT', 'TEXTAREA'].includes(e.target.tagName)) {
            const el = e.target;
            const isText = ['text', 'password', 'email', 'number', 'tel', 'url', 'search'].includes(el.type) || el.tagName === 'TEXTAREA';
            
            if (isText) {
                if (e.type === 'input') {
                    if (typeTimeout) clearTimeout(typeTimeout);
                    typeTimeout = setTimeout(() => {
                        const selector = getSelector(el);
                        const sensitive = isSensitive(el);
                        logAction({
                            action: 'TYPE',
                            selector,
                            value: sensitive ? '<Sensitive Data>' : el.value,
                            label: el.placeholder || el.name || el.getAttribute('aria-label') || el.id || ''
                        });
                    }, 500);
                    return;
                }
            }
            
            if (['checkbox', 'radio'].includes(el.type) || el.tagName === 'SELECT') {
                if (e.type !== 'change') return;
            } else if (isText) {
                if (e.type !== 'change' && e.type !== 'blur') return;
            }

            const selector = getSelector(el);
            const sensitive = isSensitive(el);
            const value = sensitive ? '<Sensitive Data>' : el.value;
            const action = el.tagName === 'SELECT' ? 'SELECT' : 'TYPE';
            const label = el.placeholder || el.name || el.getAttribute('aria-label') || el.id || '';
            
            if (el.tagName === 'SELECT') {
                const selectedOption = el.options[el.selectedIndex];
                logAction({ action: 'SELECT', selector, value: selectedOption.value, label: label, text: selectedOption ? selectedOption.text : '' });
                return;
            }

            logAction({ action, selector, value, label });
        }
    };

    document.addEventListener('input', handleInputChange, true);
    document.addEventListener('change', handleInputChange, true);
    document.addEventListener('blur', handleInputChange, true);

    // Drag and Drop support
    let dragSelector = null;
    document.addEventListener('dragstart', (e) => {
        dragSelector = getSelector(e.target);
    }, true);

    document.addEventListener('drop', (e) => {
        const dropSelector = getSelector(e.target);
        logAction({ 
            action: 'DRAG_AND_DROP', 
            selector: dragSelector, 
            target: dropSelector 
        });
        dragSelector = null;
    }, true);

    // Navigation support
    const handleNavigation = () => {
        logAction({ action: 'NAVIGATE', url: window.location.href, title: document.title });
    };
    window.addEventListener('popstate', handleNavigation);
    window.addEventListener('hashchange', handleNavigation);
    
    // Capture initial navigation if not already captured
    if (window.location.href !== 'about:blank') {
        setTimeout(handleNavigation, 500);
    }

    document.addEventListener('keydown', (e) => {
        if (e.code === 'Space') {
            const selection = window.getSelection();
            const selectedText = selection.toString().trim();
            if (selectedText) {
                let element = selection.anchorNode.parentElement;
                const selector = getSelector(element);
                const span = document.createElement('span');
                span.style.backgroundColor = 'rgba(0, 255, 0, 0.4)';
                span.style.border = '2px solid #00ff00';
                span.style.borderRadius = '2px';
                span.style.padding = '1px';
                span.style.zIndex = '9999';
                try {
                    const range = selection.getRangeAt(0);
                    range.surroundContents(span);
                    setTimeout(() => {
                        const parent = span.parentNode;
                        if (parent) {
                            while (span.firstChild) parent.insertBefore(span.firstChild, span);
                            parent.removeChild(span);
                        }
                    }, 1500);
                } catch (err) {}
                logAction({ action: 'ASSERT', text: selectedText, selector });
                e.preventDefault();
            }
        }
    });
    console.log('AI Automation Recorder: Running...');
})();
"""

class RecorderAgent:
    def __init__(self):
        self.context = None
        self.browser = None
        self.actions = []
        self.p = None
        self.status = "idle" # idle, recording, completed
        self.stop_event = asyncio.Event()

    async def _on_action(self, action):
        url = action.get('url', '').lower()
        # Filter out chrome internal pages and empty pages
        if 'chrome://' in url or 'about:blank' in url:
            return

        msg = f"🎥 [Recorder] Captured: {action.get('action')} on {action.get('selector') or url}"
        print(msg)
        from backend.utils.logger import log_to_ui
        log_to_ui(msg)

        self.actions.append(action)

    async def start_session(self):
        print("🎥 [RecorderAgent] Initializing new session...")
        config = config_manager.get_config()
        inc_mode = config.get("INC_MODE", False)

        # Cleanup any existing session first
        if self.p or self.browser or self.context:
            print("🔄 RecorderAgent: Cleaning up existing session before starting new one...")
            try:
                if self.context: await self.context.close()
                if self.browser: await self.browser.close()
                if self.p: await self.p.stop()
            except: pass
            
        self.actions = []
        self.status = "recording"
        self.stop_event.clear()
        self.p = await async_playwright().start()

        chrome_exe = config.get("CHROME_EXECUTABLE_PATH", "")
        chrome_user_data = config.get("CHROME_USER_DATA_DIR", "")
        launch_args = ["--disable-blink-features=AutomationControlled"]
        
        print(f"🚀 RecorderAgent: Starting session (Incognito: {inc_mode}, Chrome Path: {chrome_exe or 'System Default'})")

        try:
            if inc_mode:
                if "--incognito" not in launch_args:
                    launch_args.append("--incognito")
                launch_args.extend(["--no-first-run", "--no-default-browser-check", "--no-sandbox"])
                self.browser = await self.p.chromium.launch(
                    executable_path=chrome_exe if chrome_exe else None,
                    channel="chrome" if not chrome_exe else None,
                    headless=False,
                    args=launch_args
                )
                self.context = await self.browser.new_context()
            else:
                user_data_dir = chrome_user_data if chrome_user_data and os.path.exists(chrome_user_data) else os.path.join(os.getcwd(), "backend/storage/user_data")
                os.makedirs(user_data_dir, exist_ok=True)
                self.context = await self.p.chromium.launch_persistent_context(
                    user_data_dir,
                    executable_path=chrome_exe if chrome_exe else None,
                    channel="chrome" if not chrome_exe else None,
                    headless=False,
                    args=launch_args
                )
                self.browser = None

        except Exception as e:
            print(f"⚠️ RecorderAgent: Failed to launch browser with primary strategy ({e}). Falling back to fresh bundled Chromium.")
            fallback_args = ["--incognito"] if inc_mode else []
            self.browser = await self.p.chromium.launch(headless=False, args=fallback_args)
            self.context = await self.browser.new_context()

        # Context-wide setup
        await self.context.expose_function("emitRecorderAction", self._on_action)
        await self.context.add_init_script(RECORD_SCRIPT_JS)
        
        # Listen for new pages
        self.context.on("page", lambda p: asyncio.create_task(self._setup_new_page(p)))

        # Get initial page
        if self.context.pages:
            page = self.context.pages[0]
        else:
            page = await self.context.new_page()
        
        await self._setup_new_page(page)

        if self.browser:
            self.browser.on("disconnected", lambda b: asyncio.create_task(self._handle_auto_stop()))

        default_url = config.get("DEFAULT_URL", "https://www.google.com")
        print(f"🌐 Navigating to initial URL: {default_url}")
        try:
            await page.goto(default_url, wait_until="domcontentloaded", timeout=15000)
        except Exception as e:
            print(f"⚠️ Initial navigation timed out or failed: {e}")

        return page

    async def _setup_new_page(self, page):
        print(f"📄 [Recorder] Page tracked: {page.url}")
        # Inject script immediately for existing pages (init_script only works for future navigations)
        try:
            await page.evaluate(RECORD_SCRIPT_JS)
        except: pass
        page.on("close", lambda p: asyncio.create_task(self._handle_page_close(p)))

    async def _handle_page_close(self, page):
        # Small delay to see if other pages remain
        await asyncio.sleep(0.5)
        if self.context and not self.context.pages:
            print("🛑 All pages closed. Auto-stopping recorder.")
            await self._handle_auto_stop()

    async def _handle_auto_stop(self):
        if self.status == "recording":
            print("🛑 RecorderAgent: Browser/Page closed by user. Stopping session automatically...")
            await self.stop_session()

    async def stop_session(self):
        if self.status == "idle" and not self.context:
            return self.actions

        if self.status == "completed" and not self.context:
            return self.actions

        try:
            self.status = "completed"
            print(f"💾 RecorderAgent: Closing browser and context (Captured {len(self.actions)} actions)...")
            # Wait a bit for pending actions to be received
            await asyncio.sleep(1.0)
            
            # Close context first
            if self.context:
                try:
                    await self.context.close()
                except:
                    pass

            # Close browser if it's still open
            if self.browser:
                try:
                    await self.browser.close()
                except:
                    pass
            
            if self.p:
                try:
                    await self.p.stop()
                except:
                    pass
            
            self.context = None
            self.browser = None
            self.p = None
            
            print(f"📊 RecorderAgent: Sorting {len(self.actions)} actions...")
            # Ensure every action has a timestamp to avoid sort errors
            for a in self.actions:
                if 'timestamp' not in a:
                    import time
                    a['timestamp'] = int(time.time() * 1000)
            
            self.actions.sort(key=lambda x: x.get('timestamp', 0))
            print("✅ RecorderAgent: Session stopped and actions sorted.")
            return self.actions
        except Exception as e:
            print(f"❌ RecorderAgent Stop Session Error: {e}")
            import traceback
            traceback.print_exc()
            return self.actions # Return what we have anyway

recorder_agent = RecorderAgent()
